= CDJ HID Protocol
Nikolaus Einhauser
:icons: font
:toc:
:experimental:

== Background

Historically, DJ controllers (meaning hardware whose purpose is to communicate with digital DJ Software) have been using https://en.wikipedia.org/wiki/MIDI[MIDI] over USB. With increasing complexity, the protocol became a bottleneck for certain applications, causing Hardware-manufacturers to start transmitting data via https://en.wikipedia.org/wiki/Human_interface_device[HID]. This allows for comparatively simple mechanisms such as simply serializing the status of controls on the controller into a buffer of fixed format but also creating complex proprietary binary protocols involving data fragmented over multiple HID packets, handshakes, variable-length data, etc.

The PioneerDJ CDJ-2000NXS2 has many different ways to communicate with other devices such as other CDJs or Mixers. One if these methods is using a custom Network Protocol called ProDJLink whose https://djl-analysis.deepsymmetry.org/djl-analysis/startup.html[reverse engineering efforts] have inspired this project as well.

== Protocol primitives

=== Simple header

Every Packet being sent and received to and from the CDJs shares this common header:

[bytefield]
----
include::example$common_header.edn[]

(draw-packet-header "type")
(draw-box nil [{:span 14} :box-above])
(draw-box nil [:box-related {:span 16}])
(draw-box (text "Packet rest according to type (padded with " :plain [:hex "00"] ")") [ :box-related {:span 16}])
(draw-box nil [{:span 16} :box-below])

----
This format limits the maximum amount of data transmitted to 62 Bytes which is not sufficient for
transmitting larger strings or other binary data such as images. For these purposes, the protocol uses an extended header

=== Extended Header

Packets with an extended header are able to transmit stem:[(\text{0x40} - 6)*(2^(2*8)-1) = 3800972] Bytes (~3.8MB) of
data.
[bytefield]
----
include::example$common_fragmented_header.edn[]

(draw-packet-header "type" "I" "L")
(draw-box nil [{:span 10} :box-above])
(draw-box nil [:box-related {:span 16}])
(draw-box (text "Packet rest according to type (padded with " :plain [:hex "00"] ")") [ :box-related {:span 16}])
(draw-box nil [{:span 16} :box-below])
----

`L` denotes the number of packets the data following
takes up while `I` indicates the index of the packet fragment in the current stream.
Both _ushorts_ encoded in little-endian byte order.


.Currently known values for `type`
* `0xf0`: Used in Handshake procedure of host and CDJ
* `0x25`: Set on-screen BPM

=== TLV Structure

Some parts of the Protocol utilize a TLV structure:
[bytefield]
----
include::example$tlv_struct.edn[]

(tlv-struct "T" "L" #(draw-gap-inline {:borders #{:right :left :top :bottom}}))

----

These TLV structures can occur nested (for example in the handshakes TODO hyperlink)
It seems `T` only indirectly describes the actual type of data in the buffer. Instead `T`
indicates __what the data is actually used for__, which in turn describes the actual
type of the data.

== Thanks

An enormous thanks to James Elliot (https://github.com/brunchboy[@brunchboy]) from
https://deepsymmetry.org/[Deep Symmetry] for not only creating
https://github.com/Deep-Symmetry/bytefield-svg[bytefield-svg] which allowed 
me to create these awesome bytefield diagrams but also for all of 
https://djl-analysis.deepsymmetry.org/[his previous research] into the ProDJLink
Protocol as well as helping me in the setup of this wiki, using bytefield-svg
and supplying me with some USB-Captures of the XDJ-XZ.
Also thanks to mailto:ard@kwaak.net/[Ard van Breemen] for helping out with his 
in-depth knowledge of the USB protocol.